services:
  - type: web
    name: video-call-backend
    env: node
    plan: free
    region: oregon  # Change to your preferred region
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
